# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-29 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b_price', models.PositiveIntegerField(default=100)),
                ('s_price', models.PositiveIntegerField(default=110)),
            ],
        ),
    ]
